version: '3.3'
services:
  db:
    image: mysql:5.7.22
    container_name: mysql57
    restart: always
    environment:
      MYSQL_DATABASE: <%= ENV['TWI_BOT_DB_NAME_DEV'] %>
      MYSQL_USER: <%= ENV['TWI_BOT_USER_NAME_DEV'] %>
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
    - "3399:3306"
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
  # app:
  #   build: .
  #   ports:
  #     - "3333:3000"
  #   command: bundle exec rails s -b 0.0.0.0
  #   volumes:
  #     - .:/rails_app
  #   depends_on:
  #     - db
