default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  timeout: 5000

development:
  <<: *default
  # FIXME: デプロイ時にridgepoleがRailsをloadしてないためこうしているが、どうにかしたい
  database: <%= YAML.load(`rails credentials:show`)['development']['db_name'] %>
  username: <%= YAML.load(`rails credentials:show`)['development']['db_user_name'] %>
  password: <%= YAML.load(`rails credentials:show`)['development']['db_password'] %>
  port: <%= YAML.load(`rails credentials:show`)['development']['db_port'] %>

test:
  <<: *default
  database: <%= ENV['DB_NAME'] || ENV['TWI_BOT_DB_NAME_TEST'] %>
  username: <%= ENV['DB_USERNAME'] || ENV['TWI_BOT_USER_NAME_TEST'] %>

production:
  <<: *default
  database: <%= ENV['TWI_BOT_DB_NAME'] %>
  username: <%= ENV['TWI_BOT_USER_NAME'] %>
  password: <%= ENV['TWI_BOT_DB_PASSWORD'] %>
  port: 3306